modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_darkness"
version="1.0.0"
displayName="The Darkness"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="The White Ninja MC"
description='''
The Darkness adds a new dimension, its mobs and structures.
'''

[[dependencies.the_darkness]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




